title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: 
url: https://dms-r.github.io/

lowercase: false

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  